In [ ]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive
!mkdir -p git_repos
%cd git_repos


In [9]:
import numpy as np


In [10]:
array_2x2 = np.array([[1, 2], [3, 4]])
print(array_2x2)


[[1 2]
 [3 4]]


In [11]:
random_3x4 = np.random.rand(3, 4)
print(random_3x4)

[[0.0433815  0.26936118 0.28106554 0.59574834]
 [0.75134195 0.05819711 0.05194104 0.2250717 ]
 [0.87442712 0.41906516 0.97397396 0.69010447]]


In [12]:
ones_array = np.ones((2, 3))
print("Array of ones:\n", ones_array)

# Zeroes array
zeros_array = np.zeros((2, 3))
print("Array of zeroes:\n", zeros_array)

Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Array of zeroes:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
rand_6x3 = np.random.rand(6, 3)
print("Original 6x3 array:\n", rand_6x3)

transposed = rand_6x3.T
print("Transposed (3x6) array:\n", transposed)

Original 6x3 array:
 [[0.91317546 0.63713717 0.15579069]
 [0.78314576 0.75683994 0.37015104]
 [0.30443064 0.29159777 0.34209235]
 [0.20417451 0.11093996 0.26043026]
 [0.60616486 0.36730556 0.2144708 ]
 [0.77663572 0.88545294 0.82784483]]
Transposed (3x6) array:
 [[0.91317546 0.78314576 0.30443064 0.20417451 0.60616486 0.77663572]
 [0.63713717 0.75683994 0.29159777 0.11093996 0.36730556 0.88545294]
 [0.15579069 0.37015104 0.34209235 0.26043026 0.2144708  0.82784483]]


In [14]:
n, p, m = 3, 2, 4

# Random arrays
A = np.random.rand(n, p)
B = np.random.rand(p, m)

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# Dot product
dot_product = np.dot(A, B)
print("Dot product (A·B):\n", dot_product)

Matrix A:
 [[0.07084026 0.78199833]
 [0.70936278 0.96271063]
 [0.67697177 0.69366257]]
Matrix B:
 [[0.12572655 0.13365905 0.10347041 0.39902532]
 [0.16678007 0.26594038 0.42087609 0.92349438]]
Dot product (A·B):
 [[0.13932824 0.21743337 0.33645427 0.75043812]
 [0.24974669 0.35083638 0.47857995 1.17211157]
 [0.20080242 0.27495629 0.36199254 0.91072236]]
